build_platform:
  osx_arm64: osx_64
  linux_aarch64: linux_aarch64
  linux_ppc64le: linux_ppc64le
conda_forge_output_validation: true
provider:
  linux_aarch64: azure
  linux_ppc64le: azure
os_version:
  linux_64: cos7
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
bot:
  automerge: true
test: native_and_emulated
